config/routes.rb
Rails.application.routes.draw do
  root to: 'todos#index'
  resources :todos do
    resource :completion, only: [:create, :destroy]
  end
  resources :sessions
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
  def completed?
    completed_at?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_current_email

  private
    def set_current_email
      @current_email = session[:current_email]
    end

    def authenticate!
      redirect_to new_session_path unless @current_email
    end
end

app/controllers/completions_controller.rb
class CompletionsController < ApplicationController
  before_action :authenticate!
  before_action :get_todo

  def create
    mark_todo(Time.now)
    redirect_to root_path
  end

  def destroy
    mark_todo(nil)
    redirect_to root_path
  end

  private
    def get_todo
      @todo = Todo.find(params[:todo_id])
    end

    def mark_todo(time)
      @todo.completed_at = time
      @todo.save
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    session[:current_email] = params[:email]
    redirect_to root_path and return
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :authenticate!

  def index
    @todos = Todo.where(email: @current_email)
  end

  def new
    @todo = Todo.new
  end

  def create
    @todo = Todo.new(todo_params)
    @todo.email = @current_email
    @todo.save
    redirect_to root_path and return
  end

  private
    def todo_params
      params.require(:todo).permit(:title, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/completions_helper.rb
module CompletionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Easels</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1>To-Dos</h1>

    <%= yield %>
  </body>
</html>

app/views/todos/index.html.erb
<ul class="todos">
  <% @todos.each do |todo| %>
    <li class="<%= 'completed' if todo.completed? %>">
      <%= todo.title %>
      <% if todo.completed? %>
        <%= button_to "Incomplete", todo_completion_path(todo), method: :delete %>
      <% else %>
        <%= button_to "Complete", todo_completion_path(todo) %>
      <% end %>
    </li>
  <% end %>
</ul>

<%= link_to "Add a New To-Do", new_todo_path %>

app/views/todos/new.html.erb
<%= form_with model: @todo do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.submit "Add To-Do" %>
<% end %>